version: 1
disable_existing_loggers: False

formatters:
  basic:
    (): config.CustomFormatter
    format: '{asctime} [{levelname:<8}] {name}: {message}'
    datefmt: '%Y-%m-%d %H:%M:%S'
    style: '{'

  file_formatter:
    format: '[{asctime}] [{levelname:<8}] {name}: {message}'
    datefmt: '%Y-%m-%d %H:%M:%S'
    style: '{'

handlers:
  rotating_file:
    class: logging.handlers.TimedRotatingFileHandler
    formatter: file_formatter
    when: W0
    interval: 1
    backupCount: 4
    encoding: utf-8

  console:
    class: logging.StreamHandler
    formatter: basic
    stream: ext://sys.stdout

  error_file:
    class: logging.FileHandler
    formatter: file_formatter
    encoding: utf-8
    mode: w
    level: ERROR

loggers:
  discord:
    level: INFO
    handlers: [rotating_file, error_file, console]
    propagate: no

  bot:
    level: DEBUG
    handlers: [rotating_file, error_file, console]
    propagate: no

  cogs.admin:
    level: DEBUG
    handlers: [rotating_file, error_file, console]
    propagate: no

  cogs.general:
    level: DEBUG
    handlers: [rotating_file, error_file, console]
    propagate: no

  cogs.events:
    level: DEBUG
    handlers: [rotating_file, error_file, console]
    propagate: no

  bot.logic:
    level: DEBUG
    handlers: [rotating_file, error_file, console]
    propagate: no

  db.queries:
    level: DEBUG
    handlers: [rotating_file, error_file, console]
    propagate: no

  bot.unittest:
    level: INFO
    handlers: [rotating_file, error_file, console]
    propagate: no
