version: 1
disable_existing_loggers: False

formatters:
  basic:
    format: '[{asctime}] [{levelname:<8}] {name}: {message}'
    datefmt: '%Y-%m-%d %H:%M:%S'
    style: '{'

handlers:
  rotating_file:
    class: logging.handlers.TimedRotatingFileHandler
    formatter: basic
    filename: rotating_logger.log
    when: W0
    interval: 1
    backupCount: 4
    encoding: utf-8

  console:
    class: logging.StreamHandler
    formatter: basic
    stream: ext://sys.stdout

  error_file:
    class: logging.FileHandler
    formatter: basic
    filename: error_logger.log
    encoding: utf-8
    mode: w
    level: ERROR

loggers:
  discord:
    level: INFO
    handlers: [rotating_file, console, error_file]
    propagate: no

  bot.main:
    level: DEBUG
    handlers: [rotating_file, console, error_file]
    propagate: no

  bot.sql:
    level: DEBUG
    handlers: [rotating_file, console, error_file]
    propagate: no

  bot.unittest:
    level: INFO
    handlers: [rotating_file, console, error_file]
    propagate: no
